### ISSUE TITLE
Tests fail to build

### ISSUE THREAD

**Issue by tomhughes** [mapbox/mapnik-vector-tile#58]
The tests are failing to build in the 0.5.5 code:

```
In file included from ./src/vector_tile.pb.h:25:0,
                 from ./src/vector_tile_backend_pbf.hpp:12,
                 from test/vector_tile.cpp:21:
/usr/include/google/protobuf/extension_set.h:183:21: error: reference to 'vector' is ambiguous
                     vector<const FieldDescriptor*>* output) const;
                     ^
In file included from /usr/include/c++/4.8.3/vector:64:0,
                 from test/catch.hpp:355,
                 from test/vector_tile.cpp:3:
/usr/include/c++/4.8.3/bits/stl_vector.h:210:11: note: candidates are: template<class _Tp, class _Alloc> class std::vector
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
In file included from test/vector_tile.cpp:13:0:
./src/vector_tile_projection.hpp:12:37: note:                 namespace mapnik::vector { }
 namespace mapnik { namespace vector {
                                     ^
In file included from ./src/vector_tile.pb.h:25:0,
                 from ./src/vector_tile_backend_pbf.hpp:12,
                 from test/vector_tile.cpp:21:
/usr/include/google/protobuf/extension_set.h:183:21: error: 'vector' has not been declared
                     vector<const FieldDescriptor*>* output) const;
                     ^
/usr/include/google/protobuf/extension_set.h:183:27: error: expected ',' or '...' before '<' token
                     vector<const FieldDescriptor*>* output) const;
                           ^
In file included from ./src/vector_tile.pb.h:25:0,
                 from ./src/vector_tile_backend_pbf.hpp:12,
                 from test/raster_tile.cpp:12:
/usr/include/google/protobuf/extension_set.h:183:21: error: reference to 'vector' is ambiguous
                     vector<const FieldDescriptor*>* output) const;
                     ^
In file included from /usr/include/c++/4.8.3/vector:64:0,
                 from test/catch.hpp:355,
                 from test/raster_tile.cpp:3:
/usr/include/c++/4.8.3/bits/stl_vector.h:210:11: note: candidates are: template<class _Tp, class _Alloc> class std::vector
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
In file included from test/raster_tile.cpp:8:0:
./src/vector_tile_projection.hpp:12:37: note:                 namespace mapnik::vector { }
 namespace mapnik { namespace vector {
                                     ^
In file included from ./src/vector_tile.pb.h:25:0,
                 from ./src/vector_tile_backend_pbf.hpp:12,
                 from test/raster_tile.cpp:12:
/usr/include/google/protobuf/extension_set.h:183:21: error: 'vector' has not been declared
                     vector<const FieldDescriptor*>* output) const;
                     ^
/usr/include/google/protobuf/extension_set.h:183:27: error: expected ',' or '...' before '<' token
                     vector<const FieldDescriptor*>* output) const;
                           ^
```

Compiler is gcc 4.8.3 and mapnik is 2.2.
